### ISSUE TITLE
[FIXED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [martinlindhe/gohash#2]
Dear Mr. Lindhe,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by martinlindhe** [comment]
Hi @sergeevabc 
I have published binaries now for Windows & macOS, they can be downloaded at
https://github.com/martinlindhe/gohash/releases/tag/0.2.3

**Comment by martinlindhe** [comment]
Oh, also it would make me happy to hear the .exe:s works for you

**Comment by sergeevabc** [comment]
Thank you for a quick reply, @martinlindhe.
I have doubts about the appearance, but now some kind of memory leak is more important.
[Timer][1] by Igor Pavlov (7-zip developer) was used to measure execution time and memory consumption.

```console
$ timer hasher skein512-512 -i D:\Test\1500M.random --skip-newline --skip-filename
97bbd1bd4d6d389b613aead78cadd2b54406a1e9db6de3c12235cecc7ff2d30738d7453012ab8b3c86aeef6c9cf2229dcf0c2c8cc21c0ed5202fdb1df8b22e44

Kernel  Time =    10.701 =   12%
User    Time =    16.926 =   20%
Process Time =    27.627 =   32%    Virtual  Memory =   4308 MB
Global  Time =    84.286 =  100%    Physical Memory =   3147 MB
```

[1]: http://www.7-cpu.com/utils.html

**Comment by martinlindhe** [comment]
The huge memory usage is because of naive implementation, we simply read the whole file into ram. I have a plan to fix it to work on data streams directly.
mem usage would still be high for a few hash types, depending on underlying implementations.

Will have a look at mem usage

**Comment by sergeevabc** [comment]
Let’s try [Digest][1] and compare the results. Something to strive for, huh?

```console
$ timer digest skein512/512 D:\1500M.random
97bbd1bd4d6d389b613aead78cadd2b54406a1e9db6de3c12235cecc7ff2d30738d7453012ab8b3c86aeef6c9cf2229dcf0c2c8cc21c0ed5202fdb1df8b22e44

Kernel  Time =     1.216 =    6%
User    Time =     4.196 =   21%
Process Time =     5.413 =   28%    Virtual  Memory =      3 MB
Global  Time =    19.253 =  100%    Physical Memory =      5 MB
```

[1]: https://sourceforge.net/projects/filedigest/files/

**Comment by martinlindhe** [comment]
While the speed of ingest is indeed impressive, the goal of this project was first and foremost to provide an implementation of a file hasher cli written in a safe and portable language.
But, surely improvements to speed and resource usage is welcome!

**Comment by martinlindhe** [comment]
I've done a quick test locally reworking the skein-512 hash to use data streams.

I didn't run it on windows so cannot directly compare to your numbers, but here is before & after,
using a 1 GB random data file:


before:
```
time hasher skein512-512 -i 1000M-random.dat --skip-filename
c3bc8a637b437fbd646fa2817821ee8e6391458accde54efb9f4be53316dfe448aaf36d2ab494623763da0281c42f11a5608b96128a9ab54b983b8b5e17c857d
Alloc = 3145912
TotalAlloc = 4194536
Sys = 4334786
NumGC = 11

hasher skein512-512 -i 1000M-random.dat --skip-filename  3.67s user 1.26s system 102% cpu 4.821 total
```

after:
```
time hasher skein512-512 -i 1000M-random.dat --skip-filename
c3bc8a637b437fbd646fa2817821ee8e6391458accde54efb9f4be53316dfe448aaf36d2ab494623763da0281c42f11a5608b96128a9ab54b983b8b5e17c857d
Alloc = 249
TotalAlloc = 249
Sys = 1700
NumGC = 0

hasher skein512-512 -i 1000M-random.dat --skip-filename  2.15s user 0.15s system 99% cpu 2.315 total
```

the numbers are from https://golang.org/pkg/runtime/#ReadMemStats, reporting internal info about the go runtime memory usage, so in number of allocations and gc reclaims, rather than in bytes.

Need to do some clean up before pushing changes, maybe I'll get it ready tomorrow

**Comment by sergeevabc** [comment]
Being a mere user and not a developer myself (however old enough to remember [Tetris][1] on magnetic tape and then breathtaking PC [demos][2] under 100 KiB), I am not sure what “safe and portable language” means exactly, but I am dismayed the outcome is the size of 7ZIP, GPG and LAME taken together. Have you noticed the growing costs of each new programming thing that claims to be a milestone of progress to display “Hello, world”? At least Golang apps are not that sluggish like .Net or Electron, so hope dies last.

[1]: https://hooktube.com/watch?v=xz_Zeq72CEc
[2]: https://github.com/joncampbell123/dosbox-x/wiki/Guide%3AMS-DOS%3Ademoscene

**Comment by martinlindhe** [comment]
Well, the "safe and portable" part is a long and opinionated story, but it's a good thing!
Safe means that the language helps you as a developer defend yourself (and users) from making certain mistakes that often lead to very serious issues in software written in other languages, most notably C.
Portable means the applications runs on many operating systems without much/any special care when developing the app. This is traditionally troublesome.

The exe size of a golang program is perhaps big by some standards, but for me it is not a real issue any more.
There is a technical reason why the exe gets big, and it's because of alot of functionality that is baked into the go application (functionality that is usable to the developer of the app), called a [runtime](https://en.wikipedia.org/wiki/Runtime_library),
and also all the dependent functionality of the app is linked into the exe, called [static linking](https://en.wikipedia.org/wiki/Static_library), where a windows program normal loads this kind of functionality from DLL:s, weighing many megabytes.

**Comment by martinlindhe** [comment]
Okay, so I finished the changes.

I quickly tested it on a Windows VM with the `timer` util you mentioned, here is the results:

I would be interested in seeing how your test results has changed.


"hasher23.exe" is the 0.2.3 binary which you tried out yesterday, before the performance fixes:
```
PS C:\Users\vm\Desktop\x> ./timer64 .\hasher23.exe skein512-512 -i .\1000M.dat
313d307abc48d1ce7955425eeb38decbeb06d46bb60d81f83aaa39ebbfa80b27bddd5bce858d2332d36e604cf1be683428b24cd478446a66cac38a13246a53dc  .\1000M.dat


Kernel  Time =     5.250 =   18%
User    Time =     2.718 =    9%
Process Time =     7.968 =   28%    Virtual  Memory =   4249 MB
Global  Time =    28.361 =  100%    Physical Memory =   1603 MB
PS C:\Users\vm\Desktop\x> ./timer64 .\hasher24.exe skein512-512 -i .\1000M.dat
313d307abc48d1ce7955425eeb38decbeb06d46bb60d81f83aaa39ebbfa80b27bddd5bce858d2332d36e604cf1be683428b24cd478446a66cac38a13246a53dc  .\1000M.dat
```


"hasher24.exe" is 0.2.4, just released, containing the performance fixes:
```
Kernel  Time =     0.359 =   10%
User    Time =     2.046 =   58%
Process Time =     2.406 =   68%    Virtual  Memory =     11 MB
Global  Time =     3.497 =  100%    Physical Memory =      6 MB
```

Thanks for bringing this up, so I got around to fixing it!

**Comment by martinlindhe** [comment]
Ps, I also grew up with the pc demos :-)
I am sometimes trying to improve dosbox-x too: https://github.com/joncampbell123/dosbox-x/commits?author=martinlindhe

**Comment by sergeevabc** [comment]
> Safe means Go helps you as a developer defend yourself (and users) from making certain mistakes

Sounds like re-inventing a kitchen knife in a way to be able to cut, but not to injure. If you ask me, it is a lazybones’ dream. Programming language, being a way to command the machine (so tempting) to do something (presumably harmless) for humans, should be taken with caution not to become enslaved by own carelessness. Werner Heisenberg, a German Nobel laureate in physics, [once said][1]: “An expert is someone who knows some of the worst mistakes that can be made in his subject, and how to avoid them”.

As for performance of GoHash, there is a progress, Martin.

```console
$ timer hasher025 skein512-512 -i D:\Test\1500M.random --skip-newline --skip-file1
97bbd1bd4d6d389b613aead78cadd2b54406a1e9db6de3c12235cecc7ff2d30738d7453012ab8b3c86aeef6c9cf2229dcf0c2c8cc21c0ed5202fdb1df8b22e44

Kernel  Time =     0.873 =    5%
User    Time =     3.931 =   26%
Process Time =     4.804 =   32%    Virtual  Memory =     80 MB
Global  Time =    14.999 =  100%    Physical Memory =      7 MB
```

[1]: https://en.wikiquote.org/wiki/Werner_Heisenberg

**Comment by martinlindhe** [comment]
> Programming language, being a way to command the machine (so tempting) to do something (presumably harmless) for humans, should be treated with caution to not become enslaved by own absent-mindedness.

Well, the general idea about programming was for many years you just 

Nice results. Looks like we beat digest now in cpu usage :-)

**Comment by sergeevabc** [comment]
> Programming was for many years this mentality about it being super complex…

A journey of a thousand miles begins with a single step, right? Programming language is [artificial][1], so it can be studied in its entirety. And I guess it takes less time than is required to master refractive surgery or earthquake engineering. Confusing syntax or semantics might be subject to improve though. Side effect of facilitating the development, however, is a ocean-size current of abandoned, poorly designed, bulky software. Action, not preceded by vision and commitment, is akin to putting a cart before the horse.

Oh, why did you reopen the issue? Request is fulfilled, Windows binary works fine.

[1]: https://en.wikipedia.org/wiki/Programming_language#Design_and_implementation
