### ISSUE TITLE
BSD style output

### ISSUE THREAD

**Issue by grylem** [martinlindhe/gohash#3]
Hi
please add option for md5 BSD style output like
MD5 (coder.txt) = 5d094cbb586f46817b1408a6c64a5ed3
Thanks

**Comment by martinlindhe** [comment]
Version 0.2.6 has been released which adds a --bsd flag to get the BSD style output.

You can download binaries from https://github.com/martinlindhe/gohash/releases or build from source with `go get -u github.com/martinlindhe/gohash/...`
