### ISSUE TITLE
[PENDING] Coder fails to deliver sometimes

### ISSUE THREAD

**Issue by sergeevabc** [martinlindhe/gohash#5]
Dear @martinlindhe,
a few encoding schemes (base36/58, binary, decimal, octal) produce no output as follows
```
ffmpeg -loglevel error -f lavfi -i "anoisesrc=d=60:c=white:r=48000" -f s16le -c:a pcm_s16le - | coder base36
ffmpeg -loglevel error -f lavfi -i "anoisesrc=d=60:c=white:r=48000" -f s16le -c:a pcm_s16le - | coder base58
ffmpeg -loglevel error -f lavfi -i "anoisesrc=d=60:c=white:r=48000" -f s16le -c:a pcm_s16le - | coder binary
ffmpeg -loglevel error -f lavfi -i "anoisesrc=d=60:c=white:r=48000" -f s16le -c:a pcm_s16le - | coder decimal
ffmpeg -loglevel error -f lavfi -i "anoisesrc=d=60:c=white:r=48000" -f s16le -c:a pcm_s16le - | coder octal
```
Other encoding schemes work fine and instantly in this scenario.
Could you be so kind to troubleshoot?

**Comment by martinlindhe** [comment]
I'll look into this soon

**Comment by martinlindhe** [comment]
Seems to be the same issue as #4 

Coder eventually finishes, but some formats are very slow at the moment. The ffmpeg command generates a 5.8 MB data file.

**Comment by martinlindhe** [comment]
I have optimized binary, decimal and octal formats in ce37f98f8870ad7a9110a4818d063529864f1215, 30e26801e7a3cb23293d3c5638ca518a11facba3 and 8198befc9bfa832983e55e3c28c3335c7e66e08f.

Regarding base36 and base58, these are encodings used to encode very large integers and are not suited to encode any type of input.

**Comment by martinlindhe** [comment]
Please try out version 0.2.7 at https://github.com/martinlindhe/gohash/releases
