### ISSUE TITLE
coder -d z85 not decoding anything

### ISSUE THREAD

**Issue by zeptoSteve** [martinlindhe/gohash#6]
I don't know if this is the correct repository, so let me know if I should also open an issue @ tilinna/z85.

z85 data encoded with `coder z85` from piped input will not decode, under any circumstances, regardless of what string is passed.

Simple test case:

```echo "This" | coder z85 | coder -d z85```

Will give:

```2019/05/09 14:24:41 error:z85: wrongly aligned input data```

As will any input, as stated above. This is referring only to decoding, because encoding I guess works as intended(?).

To be sure, the output of:

```echo "This" | coder z85```

Is consistently:

```ra]#!3ig5a```

macOS 10.14.4, installed with `go get`.

**Comment by martinlindhe** [comment]
Thanks for your your issue report, I will take a look and if necessary pass on to tilinna/z85.

**Comment by martinlindhe** [comment]
The issue is that coder by default adds a newline after the output.

You can verify this by

    $ echo "This" | coder -n z85 | coder -d z85

I'll look more into if we can make the z85 decoder more forgiving if the input contains extra newlines.

**Comment by martinlindhe** [comment]
Issue should be resolved in 0.2.9 which you can download from https://github.com/martinlindhe/gohash/releases

Or if you are using the go command, by running the following in a terminal:

    $ go get -u github.com/martinlindhe/gohash/...
