### ISSUE TITLE
Parameter to disable color

### ISSUE THREAD

**Issue by EugeneRyabtsev** [martinlindhe/gohash#7]
Using Win64 build of v0.2.9 and calling it with my input file like "hasher streebog-256 -e hex --skip-filename", the output is like "←[1;33m620b45f87afe5ddb17ca95b91e117aa0d4eefd7ee18e74ce90178412538cb7d3←[0m", which is correct, but also includes escape sequences at the beginning and the end, which don't do any good in standard cmd.exe or when saved to a text file. Could you add a command line option to output only the hash itself, like "620b45f87afe5ddb17ca95b91e117aa0d4eefd7ee18e74ce90178412538cb7d3", list this option in --help, and maybe make it default on Windows?

**Comment by martinlindhe** [comment]
Thanks for the report!

I added --no-color switch to the hasher.exe program in 0.2.10 which you can download here: https://github.com/martinlindhe/gohash/releases/tag/0.2.10

**Comment by martinlindhe** [comment]
By the way, it seems the new Windows terrminal [1] will support ansi colors.

1: https://devblogs.microsoft.com/commandline/introducing-windows-terminal/
